name: Deploy to GCP

on:
  push:
    branches:
      - main  # 또는 배포할 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 또는 사용 중인 Node.js 버전

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GCP
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}  # 추가된 환경 변수
        run: |
          # App Engine에 배포할 때는 npm run export 명령어를 사용할 필요 없음
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
          gcloud config set project as-rudgus4620
          gcloud app deploy --quiet  # --quiet 플래그는 배포 중의 모든 프롬프트를 비활성화합니다.
